name: test
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gcc mandelbrot.c -lm
      - run: sudo apt-get install gnuplot-nox texlive
      - run: gnuplot mandelek.gpi
      - run: pdflatex latech.tex
      - run: pdflatex latech.tex
      - run: ls
      - uses: actions/upload-artifact@v4
        with:
          path: latech.pdf
